class MedicalOntology {
  static const Map<String, List<String>> unitOntology = {
    "RBC": ["10^12/L", "T/L"],
    "WBC": ["10^9/L", "G/L", "10^3/uL"],
    "HGB": ["g/L"],
    "HCT": ["%", "L/L"],
    "MCV": ["fL"],
    "MCH": ["pg"],
    "MCHC": ["g/L", "g/dL"],
    "RDW_SD": ["fL", ""],
    "RDW_CV": ["%", ""],
    "PLT": ["10^9/L", "G/L", "10^3/uL"],
    "MPV": ["fL", ""],
    "PCT": ["%"],
    "PDW": ["fL"],
    "PLCR": ["%"],
    "IG_PERCENT": ["%"],
    "IG_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "NEUT_PERCENT": ["%"],
    "NEUT_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "LYM_PERCENT": ["%"],
    "LYM_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "MONO_PERCENT": ["%"],
    "MONO_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "EOS_PERCENT": ["%"],
    "EOS_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "BASO_PERCENT": ["%"],
    "BASO_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "NRBC_PERCENT": ["%"],
    "NRBC_ABS": ["10^9/L", "G/L", "10^3/uL"],
    "UREA": ["mmol/L", "mmol/l"],
    "GLUCOSE": ["mmol/L", "mmol/l"],
    "CREATININE": ["umol/L", "umol/l", "µmol/L"],
    "NA": ["mmol/L", "mmol/l"],
    "K": ["mmol/L", "mmol/l"],
    "CL": ["mmol/L", "mmol/l"],
    "AST": ["U/L", "U/l"],
    "ALT": ["U/L", "U/l"],
    "CK_MB": ["U/L", "U/l"],
    "HBA1C": ["%"],
    "PRO_BNP": ["pg/ml", "pg/mL"],
    "TROPONIN_T": ["ng/l", "ng/L"],
    "CHOLESTEROL": ["mmol/L", "mmol/l"],
    "TRIGLYCERIDE": ["mmol/L", "mmol/l"],
    "HDL_C": ["mmol/L", "mmol/l"],
    "LDL_C": ["mmol/L", "mmol/l"],
    "URIC_ACID": ["umol/l", "umol/L", "µmol/L"],
    "FERRITIN": ["ng/ml", "ng/mL"],
    "ALBUMIN": ["g/L", "g/l"],
    "CALCIUM_ION": ["mmol/L", "mmol/l"],
    "PTH": ["pg/mL", "pmol/L", ""],
    "FT4": ["ng/dL", "ng/dl"],
    "CORTISOL": ["nmol/L", "nmol/l"],
    "TSH": ["uIU/mL", "µIU/mL", "uIU/ml"],
    "ACTH": ["pmol/l", "pmol/L"],
    "PH_BG": [""],
    "PCO2": ["mmHg"],
    "PO2": ["mmHg"],
    "SO2": ["%"],
    "HCO3": ["mmol/L", "mmol/l"],
    "THB": ["g/dL", "g/dl"],
    "COHB": ["%"],
    "O2HB": ["%"],
    "HHB": ["%"],
    "BARO": ["mbar"]
  };

  static List<String> get testOptions {
    var keys = unitOntology.keys.toList();
    keys.sort();
    return keys;
  }
}